### ISSUE TITLE
Doesn't work with spaces in directory names

### ISSUE THREAD

**Issue by rahji** [Pashgunt/cdh#1]
Type `go-dir add /home/me/folder\ with\ spaces`. The output of `cdi` is incorrect after that.

**Comment by Pashgunt** [comment]
Incorrect is it, that is, empty or it gives out some kind of error. Thanks, I'll take a look and fix it. In the near future, there are plans to cover the code with tests

**Comment by rahji** [comment]
Sorry, I uninstalled too soon. But yes, it was incorrect. I believe, with the example above, `cdi` would show `/home/me/folder`

**Comment by Pashgunt** [comment]
I am grateful for your example, it will be corrected in the near future
